name: Delete_build_test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.GoogleDrive.Delete/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.GoogleDrive.Delete
      env_var_name_1: GoogleDrive_CredBase64_Part1
      env_var_name_2: GoogleDrive_CredBase64_Part2
      env_var_name_3: GoogleDrive_FolderId
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.GOOGLEDRIVE_CREDBASE64_PART1 }}
      env_var_value_2: ${{ secrets.GOOGLEDRIVE_CREDBASE64_PART2 }}
      env_var_value_3: ${{ secrets.GOOGLEDRIVE_FOLDERID }}