name: Upload_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.GoogleDrive.Upload/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.GoogleDrive.Upload
      env_var_name_1: GoogleDrive_FolderId
      env_var_name_2: GoogleDrive_SecretJson
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.GOOGLEDRIVE_FOLDERID }}
      env_var_value_2: ${{ secrets.GOOGLEDRIVE_SECRETJSON }}